name: "Frogbot Scan Repository"
on:
  workflow_dispatch:
  schedule:
    # The repository will be scanned once a day at 00:00 GMT.
    - cron: "48 * * * *"
permissions:
  contents: write
  pull-requests: write
  security-events: write
  # [Mandatory If using OIDC authentication protocol instead of JF_ACCESS_TOKEN]
  # id-token: write
jobs:
  scan-repository:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The repository scanning will be triggered periodically on the following branches.
        branch: ["main"]
    steps:

  
    - name: Download and run Frogbot
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        JF_GIT_BASE_BRANCH: ${{ matrix.branch }}
        JF_GIT_PROVIDER: github
        JF_GIT_OWNER: BiggieFudge
        JF_GIT_REPO: golang-example
        JF_GIT_PULL_REQUEST_ID: 1
      run: |
        # Specify the version you want to download
        curl -fLg "https://releases.jfrog.io/artifactory/frogbot/v2/2.23.4/getFrogbot.sh" | sh -s 2.23.4
  
        # Assuming that the frogbot command is available after running the above script
        ./frogbot scan-repository
      
